### ISSUE TITLE
Item layout clipped by padding

### ISSUE THREAD

**Issue by hendrawd** [bloderxd/deck#2]
<img src="https://user-images.githubusercontent.com/9481791/34296929-b94cdd54-e747-11e7-88cb-8d758cd4ef11.jpeg" width="300px"/>

I think instead of
`deckPager.useDefaultPadding(context)`
developer should have an option to specify how many percent or dp of the padding directly

**Comment by hendrawd** [comment]
I could help you on this one if you want

**Comment by bloderxd** [comment]
Well, I like Pull requests :+1: ... I'm out of time this week, then if you want you can contribute.

**Comment by hendrawd** [comment]
Haha, looks like it's more complicated that i though before. I will try to experiment with it a little more

**Comment by bloderxd** [comment]
Yeah it's not a simple feature, if you want I can do this for us next week.

**Comment by hendrawd** [comment]
#4

**Comment by bloderxd** [comment]
Closed - https://github.com/bloderxd/deck/pull/4
